### PR TITLE
fix server ready detection for ember-cli < 2.13

### LINKED ISSUE #118: Timing issues
We're running into timing issues caused by [this line](https://github.com/tomdale/ember-cli-addon-tests/blob/ca4b9919fc7e2f0bbe72786d826fee5a4509fff5/lib/commands/start-server.js#L53). The problem is that `ember s` will log _"Serving on http://localhost:4200/"_ long before the server is actually ready to respond to connections. In our case from that line being logged and the server actually being ready to respond to connections it might well take more than 2 minutes (that is on our underpowered CI server). This causes requests in our FastBoot tests to time out as

```js
before(() => {
  let appPath = path.normalize(`${__dirname}/..`);
  app = new App(appPath);

  return app.startServer({
    port: 4000,
    command: 's'
  })
});
```

resolves way too early so that the tests start long before the server is actually ready.

### PR DESCRIPTION
**Pull request by marcoow**
…by waiting until the build has completed

closes #118

### CODE REVIEW

**Comment by simonihmig** [comment]
I am not sure how that fixes anything, do I miss something? Both these text pieces ("Build successful" and "Serving on") are emitted on the same line, at the same time:

```
Build successful (24649ms) – Serving on http://localhost:4200/
```

See https://github.com/ember-cli/ember-cli/blob/78324547daef8529aaec3a0cdb48b0e61fe4346b/lib/models/watcher.js#L45-L54.

**Comment by marcoow** [comment]
The 2 messages are only logged in the same line since ember-cli 2.13: https://github.com/ember-cli/ember-cli/commit/b363b7cca8a3a98211dcfaf8c6b20bbe2dbdad75

**Comment by simonihmig** [comment]
Ah, I see... so the changes are ok then I guess, but still don't solve the issue for 2.13+, so maybe we can come up with something better? 

How about waiting for the "Slowest Nodes..."  profiling output, does that make sense? (Was that always around so to not break things for even older ember-cli versions?)

Btw, we also suffered from occasional timeouts in CI for FastBoot tests. Never really digged deeper into the issue, but what you found here might explain that as well. So 👍   /cc @andreasschacht

**Comment by marcoow** [comment]
> Ah, I see... so the changes are ok then I guess, but still don't solve the issue for 2.13+, so maybe we can come up with something better?

We're running 2.12; I don't expect this to exist for > 2.12.

**Comment by simonihmig** [comment]
> We're running 2.12; I don't expect this to exist for > 2.12.

You are right of course, my bad. Newer versions emit that line after the initial build, obviously, so they should be fine then...

**Comment by kellyselden** [comment]
I think this is fine to merge without a regression test, as ember-cli doesn't have LTS versions. By the time someone in the future accidentally breaks this, @marcoow will be off this client or off ember-cli 2.12 😉

**Comment by kellyselden** [comment]
Tried to release in v0.7.1, but I don't have permissions...

**Comment by simonihmig** [comment]
Released 0.7.1!

@kellyselden just added you on npm!

**Pull request merged**
