### PR TITLE
Extract App class from AddonTestApp

### PR DESCRIPTION
**Pull request by Turbo87**
This allows us to test our real app using the same nice API as we can use for addons:

```js
  before(function() {
    app = new App(path.normalize(`${__dirname}/..`));

    return app.startServer({
      command: 'fastboot'
    });
  });
```

/cc @simonihmig

### CODE REVIEW

**Comment by marcoow** [comment]
Seems like this would require a rename of this addon actually 🙀

**Comment by Turbo87** [comment]
yeah, thought about this too... maybe `ember-cli-e2e-tests` or something like that would make more sense then 🤷‍♂️

**Comment by simonihmig** [comment]
Regarding the code I have not really anything to complain. Just the question that has already been touched here and on the Slack chat, if that is stretching the scope of the addon too much, being meant to be used for addon testing...

> Test helpers for testing Ember CLI addons inside the context of a real Ember app.

But I see the motivation here, allowing you to reuse much of the utility functions like `startServer`, `runCommand`etc. for the app testing use case. As it is just splitting the functionality (as things like the pristine app is not needed for app testing) without adding really anything specific to app testing, I would see this in a pragmatic way and accept this. But I think we should not stretch this any further in this addon. I guess there is room for some more opinionated addon focusing on FastBoot testing for apps, which could use this functionality here and add more app-testing/FastBoot specific stuff on top. 

So I would merge this if there are no vetos!? @tomdale @kellyselden

**Comment by tomdale** [comment]
Seems good to me. 👍

**Comment by simonihmig** [comment]
Published as v0.6.0. Thanks @Turbo87!

**Pull request merged**
