### PR TITLE
Fix pathing for pre-cook 🌽

### PR DESCRIPTION
**Pull request by chadhietala**

### CODE REVIEW

**Comment by chadhietala** [comment]
Actually there seems to be more issues.

**Comment by tomdale** [comment]
@chadhietala I think the issue is that `ember-cli` is a dev depency, so if this gets installed via `npm install` it won't exist. Probably the best bet :slot_machine: is to `findup` the hierarchy until `ember-cli` is found in a `node_modules` directory.

**Comment by fivetanley** [comment]
I think you want to use `require.resolve` here. I patched it locally:

```javascript
var ember = require.resolve('ember-cli/bin/ember');
```

And it works locally for me in npm3.

**Comment by tomdale** [comment]
Such deep node internals knowledge.

**Comment by fivetanley** [comment]
It was a pretty common thing when npm3 came out and is luckily public api

**Comment by tomdale** [comment]
@chadhietala ping

**Pull request merged**
