### PR TITLE
test for port cleanup

### PR DESCRIPTION
**Pull request by kellyselden**
I'm expecting this to fail.

### CODE REVIEW

**Comment by kellyselden** [comment]
Only fails in Unix.

**Comment by kellyselden** [comment]
Also only an issue with ember-cli 2.13. Rolling back to 2.12 fixes it.

**Comment by kellyselden** [comment]
@ro0gr @rwjblue Do either of you have any hints? There was a lot of work in https://github.com/ember-cli/ember-cli/blame/master/lib/utilities/will-interrupt-process.js for 2.13, and now it appears https://github.com/tomdale/ember-cli-addon-tests/blob/da194326bb27a38d5b851b069a597ce1753b817e/lib/models/app.js#L49 no longer works.

**Comment by simonihmig** [comment]
Confirm. Also seeing this in tests. The whole spawned ember process does not get shutdown, leaving the default port 49741 open. 

Also in bash I cannot `kill <num>` the process, only `kill -9 <num>` will work. Furthermore I noticed that when running `ember fastboot` in an app, I cannot terminate the process with `ctrl-c`. Also here only sending `SIGKILL` works. While everything is ok when running `ember s` (which is also running FastBoot now with the latest release). 

So this looks like an issue with ember-cli-fastboot, when running in the deprecated `ember fastboot` mode. Will investigate a bit further...

**Comment by simonihmig** [comment]
So, here we go:
* as stated in the previous command, running `ember fastboot` seems to have an issue with the latest ember-cli, not terminating the process, see https://github.com/ember-fastboot/ember-cli-fastboot/issues/386
* I created #98 to work around this, running `ember server` rather than `ember fastboot` (which is deprecated anyways) in tests

@kellyselden when we have merged #98, can you rebase then this PR, which *should* hopefully fix the test you added!

This will fix our tests here, but not those in other addons that still run the `fastboot` command. Should we care about this here, maybe by issuing a warning message?

**Comment by ro0gr** [comment]
@kellyselden haven't checked this test yet. But I will do.

@simonihmig thanks for your observations. Digging into `fastboot` command could help me to better understand what is missing in the `will-interrupt-process` stuff.

**Pull request merged**
