### PR TITLE
add an acceptance test

### PR DESCRIPTION
**Pull request by kellyselden**
generated an addon in fixtures, then used it and it's dummy app to run the tests against.

### CODE REVIEW

**Comment by simonihmig** [comment]
👍  Having some tests would be really cool. Always was afraid when contributing stuff when not being safe on not breaking things! :)

Just one objection: you are asserting the existence of the _"Congratulations, you made it!"_ string, that comes from here: https://github.com/ember-cli/ember-welcome-page/blob/40f6176130644c3583a3c70d9a0b4304218a4b2f/vendor/welcome.html#L123

When things change in this external addon (I guess changing the title there does not violate semver!? ;)) this would break tests here. Better remove that addon all together, and add an `index.hbs` with our own content used for the assertions!

**Comment by kellyselden** [comment]
Good call. Added a template to assert against.

**Comment by simonihmig** [comment]
After thinking about this a little bit more, I just wonder if it is the right way to check in all the addon boilerplate into git. Another way would be to programmatically create the addon in the tests `before` hook with a call to `ember addon ...` (probably with all the `--skip-*` flags) and overwrite the things you want to have changed (like your `application.hbs`). Would be very similar to what is already happening with the pristine app and its "fixtures".

Would keep the repo cleaner. However I would not insist on this. Better have this now than a possibly "better" solution too late. We can still refactor...

Your thoughts? @tomdale @danmcclain

**Comment by kellyselden** [comment]
@simonihmig I like that idea, but then changing the addon, like adding the testing template, gets more complicated.

**Comment by tomdale** [comment]
👍 Thank you!

**Comment by simonihmig** [comment]
@kellyselden The tests are failing on Travis, also on my local machine. Did this work for you?

After looking at it more deeply, I see some issues:
* the failing point is the call to `findAddonPackageJSONPath`, it does not find the addon's `package.json`. It assumes that `ember-cli-addon-tests` lies in the `node_modules` folder of the addon under test, which is obviously not the case here. Maybe this should be configurable to make this work for our test case?
* what is this supposed to do? https://github.com/tomdale/ember-cli-addon-tests/pull/18/files#diff-c773c0c6b13b4a029f354d62c034c489R20
* The test assertion looks for some output that should come from dummy app's `application.hbs`, but the dummy app will not be involved when building the temporary app. The tests run in the context of this temporarily created app, that consumes the addon under test. So we can assume things the addon exposes under its `app` tree to be present in the temporary app. But nothing from the dummy app.

Or do I miss something?

**Comment by tomdale** [comment]
@simonihmig Yeah, I'm seeing the same thing. I was planning to make the addon path overridable for this use case, although I'm now wondering how it was ever working for @kellyselden. ;)

If I'm understanding the structure correctly, `test/fixtures/my-addon` contains an addon. `test/fixtures/tests/dummy` contains a stub Ember.js app used to test the test addon. The tests are run in the context of the test addon (see https://github.com/tomdale/ember-cli-addon-tests/blob/master/test/acceptance/application-test.js#L15), so it creates a "dummy" app based that addon.

Put another way, I think it's laid out this way to:

1. Re-use the default Ember CLI file system layout.
2. Use the "fixtures" API in ember-cli-addon-tests to create a new pristine app then copy over the "dummy" app on top as a fixture.

So I *think* everything looks OK, except for the problem of finding the `package.json`, which again, I'm not sure how it was ever supposed to work. But I just wanted to have _some_ tests in place, and then iterate on them from there. (And you were right earlier, I somehow turned off watching for this repo—sorry about that!)

**Comment by simonihmig** [comment]
@tomdale Ok, got it, was a little bit confused probably, makes a lot more sense to me now! Sorry @kellyselden for getting this wrong.

So, for the addon path, shall we just add another (optional) key `addonPath` to the options hash? Could do this if nobody else wants to take over!? :)

**Comment by kellyselden** [comment]
FYI I've started looking into this. I know it was working when I wrote it, but I see that it's not working anymore. I might have had another one of my branches mixed in, then when I starting extracting them for individual PRs, it stopped working.

**Pull request merged**
