### PR TITLE
add skipNpm option

### PR DESCRIPTION
**Pull request by kellyselden**
avoid double `npm install` calls if you know you are going to manually manipulate package.json later.

cc @cibernox I know you will like this feature.

### CODE REVIEW

**Comment by cibernox** [comment]
Yep, thanks!

**Comment by simonihmig** [comment]
I like the changes here in general, but there is one thing to note: as I also mentioned in a chat with @cibernox, we run the addon's default blueprint when setting up the app [here](https://github.com/tomdale/ember-cli-addon-tests/pull/131/files#diff-32914fa89b187f0dba3ec3832f5ad335R115), and as this will spawn ember-cli, this will fail without installed dependencies. It will actually be catched, so this will not break the promise chain, but the default blueprint will still not have been run, so for addons that rely on that (e.g. to install bower stuff) this will fail. 

At least we should mention that in the Readme. Or maybe try to check if the addon actually has a default blueprint in advance and run `npm install` in this case even if `skipInstall` is set?

**Comment by kellyselden** [comment]
I changed to skipNpm because I don't think affecting bower is a good idea. A skipBower can be added later if someone really wants it.

**Comment by kellyselden** [comment]
@simonihmig I could add a README note, and also run `ember help generate --json` to look for a default blueprint. It will add a bit of latency to start ember-cli, but not bad.

**Comment by simonihmig** [comment]
That `ember help generate --json` would then run in the context of the original addon, not in the tmp app (where we have no deps installed), right? Sounds interesting, but I guess we can leave that for another PR and get this merged with just a notice for now?

Btw, build is failing because of some ESLint issues (`debugger` statement ;))

**Comment by kellyselden** [comment]
Sorry about that, I'm experimenting with messaging in the catch statement.

**Comment by kellyselden** [comment]
This is currently blocked on #133 so I can get a blueprint test in.

**Comment by kellyselden** [comment]
@simonihmig I'm testing this with a default blueprint. It is running the blueprint, and it never hits that catch. Maybe I am missing something.

**Comment by simonihmig** [comment]
@kellyselden yeah, IIRC that was added to catch running `ember g my-addon` when `my-addon` does *not* have a default blueprint! We don't know if it has one, so we just try and ignore any errors. 

Certainly not ideal, if we have a way to check if an addon has a default blueprint, we could only run that blueprint in this case (without catching).

**Comment by kellyselden** [comment]
That's a little different than the scenario I'm seeing. I'm seeing that with a default blueprint present and skipInstall turned on, it is working and running the blueprint, not failing because of missing dependencies like you suggested.

**Comment by kellyselden** [comment]
Here is a log example of a failed blueprint run because of missing dependencies https://travis-ci.org/tomdale/ember-cli-addon-tests/jobs/261336114#L315-L329

**Comment by kellyselden** [comment]
I think they can succeed if they are not pulling in any dependencies, even when skipInstall is on. So not running them when skipInstall is on might be too much.

**Comment by simonihmig** [comment]
@kellyselden Good to know, thanks for digging into this! 👍 I think this is good to merge, from my POV.

I use this lib for https://github.com/kaliber5/ember-fastboot-addon-tests, where I cannot make assumptions about the addons blueprint, like if it has a default blueprint (could check that though) and what that does. So even though I add FastBoot to package.json and run `npm install` afterwards, I probably cannot use the skip flag. But for those cases where you use e-c-a-t directly on an addon which you know what it does, this should be safe to use.

**Comment by kellyselden** [comment]
@simonihmig Makes sense that you wouldn't want to use it in that case.

**Pull request merged**
