### PR TITLE
Document precook-node-modules script

### LINKED ISSUE #90: Document precook-node-modules script
Ref: https://github.com/ember-fastboot/ember-cli-fastboot/blob/30b9d5d96494ccc59810281c40330c2d1c29080e/README.md#tests

This is currently only used by ember-cli-fastboot but is likely beneficial to anyone that uses this addon.

### PR DESCRIPTION
**Pull request by trentmwillis**
Fixes #90.

### CODE REVIEW

**Comment by trentmwillis** [comment]
@simonihmig would you mind verifying that I correctly captured the functionality of this script?

**Comment by simonihmig** [comment]
@trentmwillis I was not involved in this project at all when this was created, and never used that script by myself. Just realized that it was referenced by ember-cli-fastboot some day, so not the best person to talk to regarding this...

It seems it is pretty much coupled to ember-cli-fastboot, see https://github.com/tomdale/ember-cli-addon-tests/blob/master/scripts/precook-node-modules.js#L23. Don't know if that is actually usable in a different context. Maybe @tomdale can shed some light?

On a different note, from what I have gathered @kratiahuja and @stefenpenner talked about refactoring the tests inside ember-cli-fastboot at least to some extend away from using this addon, instead running tests on the dummy app, so maybe the days of this script are counted!? :)

**Comment by trentmwillis** [comment]
I think we can decouple the script to make it usable for other addons (seems like an easy change).

Yes, I am aware of some of the ideas for refactoring the tests for FastBoot, but I imagine some end-to-end tests leveraging this will likely remain for some time. Additionally, this will likely continue to be used by ember-engines for a while.

**Comment by stefanpenner** [comment]
> so maybe the days of this script are counted!? :)

Im not 100% sure, but I believe so.

**Comment by simonihmig** [comment]
> some end-to-end tests leveraging this will likely remain for some time

Sure, did not want to question the existence of the whole addon (need this as well), just of this (right now coupled) script.

**Comment by stefanpenner** [comment]
@simonihmig if you have time, I would love for you to provide the use-cases where you need this add-on. Its totally possible I am missing something important, rendering my above suggestion invalid.

**Comment by kratiahuja** [comment]
I think this addon is mainly needed to test fastboot with canary Version of ember and canary version of ember data. Of course it's API can also take in a version of ember to test against. 

This is to make sure the visit API never regress and fastboot breaks. However, the same can also be tested with the addon having a canary version of ember so that its dummy app will pick canary. We then don't need to create the app for every test suite. There maybe some sanity tests that still need to be written with this addon but a bulk of them can be written against the dummy app.

**Comment by simonihmig** [comment]
> if you have time, I would love for you to provide the use-cases where you need this add-on.

@stefanpenner Put something together here #104 as a starting point, let's move the general discussion over there! :)

**Comment by trentmwillis** [comment]
I've genericized the script so that it is no longer ember-cli-fastboot specific. We'll be able to leverage this in ember-engines now as well and since this won't be going away in the immediate future I plan to merge once CI is green.

**Comment by simonihmig** [comment]
LGTM

@trentmwillis just curious, as I have never used this before, how do you use it, just when developing locally, not in CI (where the precooked tmp folder will not survive containerized build runs), right?

**Comment by tomdale** [comment]
The idea of "precooking" is a development-time feature meant to speed things up. It basically just caches an app at that version. You wouldn't use it in CI because it doesn't invalidate the cache when a new version comes out.

**Comment by simonihmig** [comment]
@tomdale thanks for clarification, makes sense!

**Pull request merged**
